spring:
  application:
    name: software-colombia-technical-test
    base-path: ${APP_BASE_PATH}
  jackson:
    serialization:
      write-dates-as-timestamps: false

  r2dbc:
    url: r2dbc:postgresql://${DATABASE_ENDPOINT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

security:
  jwt:
    secret: ${JWT_SECRET}
  public-paths:
    - ${APP_BASE_PATH}/auth/login

#logging:
#  level:
#    org.springframework.security: TRACE
#    org.springframework.web.reactive: DEBUG